services:
  db:
    image: postgres:17  # Променено от 18 на 17 за стабилност
    environment:
      POSTGRES_DB: qc_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    # Указваме на Docker, че командите се изпълняват в /app (където е manage.py)
    working_dir: /app
    entrypoint: ./entrypoint.sh
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/qc_db
      DEBUG: "False"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
