services:
  db:
    image: postgres:17  # Променено от 18 на 17 за стабилност
    environment:
      POSTGRES_DB: qc_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/qc_db
      DEBUG: "False"
    depends_on:
      - db


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
