# Generated by Django 6.0.3 on 2026-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('qc', 'Quality Control'), ('manager', 'Manager'), ('admin', 'Administrator'), ('qc manager', 'QC Manager'), ('supervisor', 'Supervisor'), ('team leader', 'Team Leader'), ('colourman', 'Colourman'), ('production manager', 'Production Manager')], max_length=20),
        ),
    ]
