# Generated by Django 6.0.3 on 2026-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblog',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
