# Generated by Django 6.0.3 on 2026-03-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('traidingparties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additive',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='traidingparties.supplier'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='traidingparties.supplier'),
        ),
    ]
