name: Deploy to Local Windows Server

on:
  push:
    branches: [ "master" ]  # Изпълнява се само при push в master клона

jobs:
  deploy:
    runs-on: self-hosted  # ТОВА КАЗВА: ИЗПЪЛНИ КОДА НА МОЯ WINDOWS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose
        shell: powershell
        run: |
          # Отиваме в папката, където GitHub е свалил проекта
          cd "C:\actions-runner\_work\QCMonitotingSystem\QCMonitotingSystem"
          
          # Стартираме Docker
          docker-compose down
          docker-compose up -d --build

